require("globals")

require("plugins.nvim-treesitter")
require("plugins.tiny-inline")
require("blink.cmp")
require("plugins.colorizer")
require("plugins.snacks")
require("plugins.mini")
require("plugins.nvim-universal-clipboard")
require("plugins.whichkey")
require("plugins.conform")
require("plugins.lualine")
require("lsp")
